In [1]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

In [2]:
import pandas as pd
from textblob import TextBlob
from google.colab import files

In [3]:
uploaded = files.upload()

Saving ALL_FULL_DATA MODIFIED.xlsx to ALL_FULL_DATA MODIFIED.xlsx

In [5]:
df = pd.read_excel("ALL_FULL_DATA MODIFIED.xlsx")

In [6]:
df_300 = df.iloc[300:600].copy()

In [8]:
def label_sentiment(text):
    polarity = TextBlob(str(text)).sentiment.polarity

    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

In [10]:
df_300["Sentiment"] = df_300[""].apply(label_sentiment)

In [16]:
columns_to_drop = [col for col in df_300.columns if 'Unnamed:' in col]
df_300 = df_300.drop(columns=columns_to_drop)
print(df_300.columns.tolist())

['paper_name', 'url', 'headline', 'article', 'publication_date', 'Sentiment']

In [17]:
print(df_300.columns.tolist())

['paper_name', 'url', 'headline', 'article', 'publication_date', 'Sentiment']

In [18]:
display(df_300.head())

,paper_name,url,headline,article,publication_date,Sentiment
300,thedailystar,https://www.thedailystar.net/business/news/tk-...,Tk 4 lakh crore default loans stuck in lawsuits,"Bangladesh Bank data show that as of June, 222...",2025-12-07 21:32:00,Positive
301,thedailystar,https://www.thedailystar.net/business/news/ris...,Rising food prices push inflation to 8.29% in Nov,Inflation in Bangladesh rose to 8.29 percent i...,2025-12-08 00:00:00,Positive
302,thedailystar,https://www.thedailystar.net/business/news/inf...,Inflation still strains US consumers,US consumer pricing and sentiment reports rele...,2025-12-08 00:00:00,Positive
303,thedailystar,https://www.thedailystar.net/business/news/gol...,Gold’s bubble behaviour may signal paradigm shift,Assets that rise rapidly above their long-term...,2025-12-08 00:00:00,Positive
304,thedailystar,https://www.thedailystar.net/business/news/fou...,Four exporters receive HSBC excellence awards,The Hongkong and Shanghai Banking Corporation ...,2025-12-08 00:00:00,Positive

In [19]:
sentiment_counts = df_300['Sentiment'].value_counts()
display(sentiment_counts)

Sentiment
Positive    259
Negative     31
Neutral      10
Name: count, dtype: int64

In [20]:
df_300

,paper_name,url,headline,article,publication_date,Sentiment
300,thedailystar,https://www.thedailystar.net/business/news/tk-...,Tk 4 lakh crore default loans stuck in lawsuits,"Bangladesh Bank data show that as of June, 222...",2025-12-07 21:32:00,Positive
301,thedailystar,https://www.thedailystar.net/business/news/ris...,Rising food prices push inflation to 8.29% in Nov,Inflation in Bangladesh rose to 8.29 percent i...,2025-12-08 00:00:00,Positive
302,thedailystar,https://www.thedailystar.net/business/news/inf...,Inflation still strains US consumers,US consumer pricing and sentiment reports rele...,2025-12-08 00:00:00,Positive
303,thedailystar,https://www.thedailystar.net/business/news/gol...,Gold’s bubble behaviour may signal paradigm shift,Assets that rise rapidly above their long-term...,2025-12-08 00:00:00,Positive
304,thedailystar,https://www.thedailystar.net/business/news/fou...,Four exporters receive HSBC excellence awards,The Hongkong and Shanghai Banking Corporation ...,2025-12-08 00:00:00,Positive
...,...,...,...,...,...,...
595,The Business Standard,https://www.tbsnews.net/economy/bb-board-clear...,"BB board clears path for NBFI liquidation, pro...",The Bangladesh Bank is set to begin the initia...,2025-12-01 00:00:00,Negative
596,The Business Standard,https://www.tbsnews.net/economy/foreign-consul...,Foreign consultant-dependent projects need to ...,Bangladesh has followed a flawed policy for ma...,2025-12-01 00:00:00,Positive
597,The Business Standard,https://www.tbsnews.net/economy/rice-and-fish-...,"Rice and fish drive food inflation in October,...",Rice and fish remained the major drivers of fo...,2025-12-01 00:00:00,Positive
598,The Business Standard,https://www.tbsnews.net/economy/ecnec-approves...,Ecnec approves 18 development projects worth o...,The Executive Committee of the National Econom...,2025-12-01 00:00:00,Positive
599,The Business Standard,https://www.tbsnews.net/economy/banking-sector...,Banking sector needs 5-10 years to recover fro...,Highlights Bangladesh Bank Governor Ahsan H Ma...,2025-11-29 00:00:00,Positive

In [21]:
df_300.to_csv("300_labeled_dataset.csv", index=False)
files.download("300_labeled_dataset.csv")